### ISSUE TITLE
Get started issues

### ISSUE THREAD

**Issue by ludovicc** [arkhn/fhir-pipe#26]
### Context of the Issue
I'm trying to follow the Get started instructions, but I run into problems

### Expected & current behavior

Please describe the behavior you are expecting. What is the current behavior?

Executing the following lines:

```
docker exec -ti arkhn-pipe-mimic /bin/bash
root@d283a9d175d9:/app# fhirpipe-run --project=Mimic --resource=Patient --main-table=Patients --use-graphql-file=True
```

This command fails with the error message:

```
/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Launching query...
Traceback (most recent call last):
  File "/usr/local/bin/fhirpipe-run", line 11, in <module>
    load_entry_point('fhirpipe==0.1', 'console_scripts', 'fhirpipe-run')()
  File "/usr/local/lib/python3.7/site-packages/fhirpipe-0.1-py3.7.egg/fhirpipe/console/run.py", line 87, in run
    rows = fhirpipe.load.sql.run(sql_query)
  File "/usr/local/lib/python3.7/site-packages/fhirpipe-0.1-py3.7.egg/fhirpipe/load/sql.py", line 115, in run
    with get_connection(connection) as connection:
  File "/usr/local/lib/python3.7/site-packages/fhirpipe-0.1-py3.7.egg/fhirpipe/load/sql.py", line 53, in get_connection
    return lib.connect(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

```

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug.

fhirbase does not seem to work:

```
docker-compose logs fhirbase
Attaching to fhir-pipe-fhirbase
fhir-pipe-fhirbase  | pg_ctl: another server might be running; trying to start server anyway
fhir-pipe-fhirbase  | waiting for server to start....2019-04-25 21:53:31.784 UTC [9] LOG:  listening on IPv4 address "0.0.0.0", port 5432
fhir-pipe-fhirbase  | 2019-04-25 21:53:31.785 UTC [9] LOG:  listening on IPv6 address "::", port 5432
fhir-pipe-fhirbase  | 2019-04-25 21:53:31.868 UTC [9] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
fhir-pipe-fhirbase  | 2019-04-25 21:53:32.649 UTC [10] LOG:  database system was interrupted; last known up at 2018-10-08 16:23:20 UTC
fhir-pipe-fhirbase  | ........................................................... stopped waiting
fhir-pipe-fhirbase  | pg_ctl: server did not start in time
fhir-pipe-fhirbase  | pg_ctl: another server might be running; trying to start server anyway
fhir-pipe-fhirbase  | waiting for server to start....2019-04-25 21:54:34.866 UTC [9] LOG:  listening on IPv4 address "0.0.0.0", port 5432
fhir-pipe-fhirbase  | 2019-04-25 21:54:34.866 UTC [9] LOG:  listening on IPv6 address "::", port 5432
fhir-pipe-fhirbase  | 2019-04-25 21:54:35.556 UTC [9] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
fhir-pipe-fhirbase  | ..2019-04-25 21:54:36.643 UTC [10] LOG:  database system was interrupted; last known up at 2018-10-08 16:23:20 UTC

```

### Steps to Reproduce (for bugs)

Please provide detailed steps for reproducing the issue. (for bugs)

**Comment by simonvadee** [comment]
fhir-pipe does not rely on fhirbase anymore, this is no longer relevant.
